name: build

on:
  push:
    tags:
      - '*'

jobs:
  build-rotateproxy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          goarch: mips32le
          version: latest
          args: release --clean
          workdir: cmd/rotateproxy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
